services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sol
      POSTGRES_PASSWORD: sol
      POSTGRES_DB: sol_de_manana
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
