-- AlterTable
ALTER TABLE "Chat" ADD COLUMN     "dailyMessageCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "dailyResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "plan" TEXT NOT NULL DEFAULT 'free';
